# SQL Lineage Mapper Locations
sql_folder_path: "mock-files/SQL-files"
lineage_output_path_file: "lineage_mapper/output/lineage.md"

# Quality Checks Locations
db_config_path: "db_details.yml"
table_configs_path: "checks/"
custom_tests_path: "custom_tests/"