table_configs_path: "checks/"
custom_checks_path: "checks/custom_checks/"

# Example database connection details
db_config:
##########
# DuckDB #
##########
  type: duckdb
  database_file: "data_quality_test.duckdb"

#############
# Snowflake #
#############
# Snowflake Database Configuration
  # type: "snowflake"
  # user: "SNOWFLAKE_USER"
  # password: "SNOWFLAKE_PASSWORD"
  # account: "SNOWFLAKE_ACCOUNT"    # Example: xy12345.us-east-1
  # warehouse: "SNOWFLAKE_WAREHOUSE"
  # database: "SNOWFLAKE_DATABASE"
  # schema: "SNOWFLAKE_SCHEMA"      # Optional, defaults to PUBLIC
  # role: "SNOWFLAKE_ROLE" 
